#!/usr/bin/env python

from __future__ import with_statement

from optparse import OptionParser

option_parser = OptionParser(description = "GStreamer-based player with variable-speed playback support",
                             usage = "%prog [options] [ mediafile.ext | playlist.m3u ]", version = "%prog 1.0")
(prog_options, prog_args) = option_parser.parse_args()

import sys, os
import pygtk, gtk, gobject

import pygst; pygst.require("0.10")
import gst

class GTK_Main:
  def set_app_state(self, state):
    if state == "STOP":
      if self.timeout:
        gobject.source_remove(self.timeout)
        self.timeout = None
      self.duration = None
      self.jump_to = None
      self.play_button.set_label(">")
      self.toggle_controls (True)
      self.pos_slider.set_value (0)
      self.player.set_state(gst.STATE_NULL)
    elif state == "PLAY":
      self.play_button.set_label("||")
      self.toggle_controls (False)
      self.player.set_state(gst.STATE_PAUSED if self.app_state == "STOP" else gst.STATE_PLAYING)
    elif state == "PAUSE":
      self.play_button.set_label(">")
      self.toggle_controls (True)
      self.player.set_state(gst.STATE_PAUSED)
    self.app_state = state
    print self.app_state

  def __init__(self, options, args):
    self.timeout = None
    self.last_folder = None
    self.rate = 1.0
    self.playlist = []; self.playlist_idx = -1

    window = gtk.Window(gtk.WINDOW_TOPLEVEL)
    self.window = window
    window.set_title("Playbin Player")
    window.set_default_size(240, 240)
    window.connect("destroy", gtk.main_quit, "WM destroy")

    vbox = gtk.VBox()
    window.add(vbox)
    self.control_panel = gtk.VBox ()
    self.movie_window = gtk.DrawingArea()
    vbox.add_with_properties(self.control_panel, "expand", False)
    vbox.add_with_properties(self.movie_window, "expand", True)
    vbox = self.control_panel

    hbox = gtk.HBox()
    vbox.add (hbox)
    self.prev_button = gtk.Button("<<")
    self.prev_button.connect("clicked", self.on_prev)
    hbox.add_with_properties(self.prev_button, "expand", False)
    self.entry = gtk.Entry()
    hbox.add(self.entry)
    self.open_button = gtk.Button("Open")
    self.open_button.connect("clicked", self.do_open)
    hbox.add_with_properties(self.open_button, "expand", False)
    self.play_button = gtk.Button(">")
    self.play_button.connect("clicked", self.on_play)
    hbox.add_with_properties(self.play_button, "expand", False)
    self.stop_button = gtk.Button("Stop")
    self.stop_button.connect("clicked", self.on_stop)
    hbox.add_with_properties(self.stop_button, "expand", False)
    
    self.iofn_hbox = gtk.HBox()
    self.iofn_hbox.hide ()
    hbox.add_with_properties(self.iofn_hbox, "expand", False)
    self.iofn_spin = gtk.SpinButton (gtk.Adjustment (1, 1, 10000, 1, 5, 0), 0, 0)
    self.iofn_spin.set_wrap (True)
    self.iofn_spin.connect ("value-changed", self.on_iofn_changed)
    self.iofn_hbox.add_with_properties(self.iofn_spin, "expand", False)
    self.ofn_label = gtk.Label ()
    self.iofn_hbox.add_with_properties(self.ofn_label)
    
    self.next_button = gtk.Button(">>")
    self.next_button.connect("clicked", self.on_next)
    hbox.add_with_properties(self.next_button, "expand", False)

    hbox = gtk.HBox()
    vbox.add (hbox)
    self.slow_button = gtk.Button("Slower")
    self.slow_button.connect("clicked", self.slower)
    hbox.add_with_properties(self.slow_button)
    self.speed1_button = gtk.Button("1x")
    self.speed1_button.connect("clicked", self.normal_speed)
    hbox.add(self.speed1_button)
    self.fast_button = gtk.Button("Faster")
    self.fast_button.connect("clicked", self.faster)
    hbox.pack_end(self.fast_button)

    hbox = gtk.HBox()
    vbox.add (hbox)
    self.on_backward_button = gtk.Button ("<-")
    self.on_backward_button.connect("clicked", self.on_backward)
    hbox.add_with_properties(self.on_backward_button, "expand", False)
    self.pos_slider = gtk.HScale (gtk.Adjustment (0.0, 0.0, 101.5, 0.5, 2.0, 1.5))
    self.pos_slider.set_update_policy(gtk.UPDATE_DISCONTINUOUS)
    self.pos_slider.connect ("change-value", self.on_change_position1)
    self.pos_slider.connect ("value-changed", self.on_change_position2)
    hbox.add (self.pos_slider)
    self.on_forward_button = gtk.Button ("->")
    self.on_forward_button.connect("clicked", self.on_forward)
    hbox.add_with_properties(self.on_forward_button, "expand", False)

    self.movie_window.connect("button_press_event", self.on_movie_clicked)
    self.movie_window.set_events(gtk.gdk.BUTTON_PRESS_MASK)

    self.player = gst.element_factory_make("playbin2", "player")
    bus = self.player.get_bus()
    bus.add_signal_watch()
    bus.connect("message", self.on_message)
    bus.enable_sync_message_emission()
    bus.connect("sync-message::element", self.on_sync_message)

    self.set_app_state("STOP")
    window.show_all()
    print args
    if len (args) > 0:
      self.open_something(os.path.abspath (args [0]))

  def do_open(self, w):
    chooser = gtk.FileChooserDialog(title = "Open", action = gtk.FILE_CHOOSER_ACTION_OPEN,
                                    buttons = (gtk.STOCK_CANCEL, gtk.RESPONSE_CANCEL, gtk.STOCK_OPEN, gtk.RESPONSE_OK))
    chooser.set_show_hidden (True)
    if (self.last_folder): chooser.set_current_folder (self.last_folder)
    if chooser.run () == gtk.RESPONSE_OK:
      self.open_something(chooser.get_filename())
    chooser.destroy()

  def get_iofn_pl_pos(self):
    return int (self.iofn_spin.get_value ()) - 1
  def on_next(self, w):
    if len (self.playlist) == 0: return
    if self.app_state != "STOP": self.set_app_state ("STOP")
    if self.playlist_idx < len(self.playlist) - 1:
      self.playlist_idx = self.playlist_idx + 1
      if self.playlist_idx != self.get_iofn_pl_pos():
        self.iofn_spin.set_value (self.playlist_idx + 1)
      self.open_file(self.playlist [self.playlist_idx])
  def on_prev(self, w):
    if len (self.playlist) == 0: return
    if self.app_state != "STOP": self.set_app_state ("STOP")
    if self.playlist_idx > 1:
      self.playlist_idx = self.playlist_idx - 1
      if self.playlist_idx != self.get_iofn_pl_pos():
        self.iofn_spin.set_value (self.playlist_idx + 1)
      self.open_file(self.playlist [self.playlist_idx])
  def on_iofn_changed(self, w, *args):
    i = self.get_iofn_pl_pos()
    print "Spun to %d" % i
    if i != self.playlist_idx:
      if self.app_state != "STOP": self.set_app_state ("STOP")
      self.playlist_idx = i
      self.open_file(self.playlist [self.playlist_idx])
    return True

  def open_something(self, filepath):
      if filepath [-4:] == ".m3u":
        self.open_playlist(filepath)
      else:
        self.iofn_hbox.hide ()
        self.open_file(filepath)
        
  def open_file(self, filepath = None):
    if filepath:
      self.entry.set_text (filepath)
    else:
      filepath = self.entry.get_text()
    print "File %s" % (filepath)
    self.last_folder = os.path.dirname(filepath)
    self.start_playbin(filepath)
    
  def open_playlist(self, filepath):
    (pl_dir, _) = os.path.split (filepath)
    with open (filepath) as fpl:
      self.playlist = list (os.path.join (pl_dir, fn.rstrip ("\n")) for fn in fpl)
    self.last_folder = os.path.dirname(filepath)
    self.ofn_label.set_text ("of " + str (len (self.playlist)))
    self.iofn_spin.set_range (1, len (self.playlist))
    self.iofn_hbox.show ()
    self.playlist_idx = -1
    self.on_next(None)

  def start_playbin(self, filepath):
    if os.path.isfile(filepath): filepath = "file://" + filepath
    self.player.set_property("uri", filepath)
    self.timeout = gobject.timeout_add_seconds (1, self.update_ui)
    self.player.set_state(gst.STATE_PAUSED)
    self.set_app_state("PLAY")

  def update_ui (self):
    if self.player.get_state() [1] == gst.STATE_PLAYING:
      if self.jump_to is None:
        pos = 100.0 * self.player.query_position (gst.FORMAT_TIME, None) [0] / self.duration
        self.pos_slider.set_value (pos)
    return True

  def on_play(self, w):
    if self.app_state == "PAUSE":  # unpause
      self.set_app_state("PLAY")
    elif self.app_state == "STOP":  # start (again)
      self.open_file()
      self.set_app_state("PLAY")
    else:  # pause
      self.set_app_state("PAUSE")

  def on_stop(self, w):
    self.set_app_state("STOP")

  def change_rate(self, rate, pos = None):
    self.rate = rate; print "Rate %s" % (self.rate)
    if pos is None:
      pos = self.player.query_position(gst.FORMAT_TIME, None)[0]
    self.player.seek (self.rate, gst.FORMAT_TIME, gst.SEEK_FLAG_FLUSH,
                      gst.SEEK_TYPE_SET, pos,
                      gst.SEEK_TYPE_NONE, -1)
  def faster(self, w):
    self.change_rate (self.rate * 1.1)
  def slower(self, w):
    self.change_rate (self.rate / 1.1)
  def normal_speed(self, w):
    self.change_rate (1.0)

  def on_change_position1(self, w, *args):
    self.jump_to = self.pos_slider.get_value ()

  def on_change_position2(self, w, *args):
    if self.jump_to:
      #pos_int = self.player.query_position(gst.FORMAT_TIME, None)[0]
      #print "Jump %s -> %s" % (pos_int, self.duration * self.jump_to / 100)
      self.player.seek (self.rate, gst.FORMAT_TIME, gst.SEEK_FLAG_FLUSH,
                        gst.SEEK_TYPE_SET, self.duration * self.jump_to / 100,
                        gst.SEEK_TYPE_NONE, -1)
      self.jump_to = None

  def forward_backward(self, w, delta):
    pos_int = self.player.query_position(gst.FORMAT_TIME, None)[0]
    self.player.seek (self.rate, gst.FORMAT_TIME, gst.SEEK_FLAG_FLUSH,
                      gst.SEEK_TYPE_SET, pos_int + delta,
                      gst.SEEK_TYPE_NONE, -1)

  def on_forward(self, w):
    self.forward_backward(w, 5000000000)
  def on_backward(self, w):
    self.forward_backward(w, -5000000000)

  def toggle_controls(self, make_visible = None):
    if make_visible is None:
      make_visible = not self.control_panel.props.visible  # toggle
    if make_visible:
      self.control_panel.show()
      self.window.unfullscreen()
    else:
      self.control_panel.hide()
      self.window.fullscreen()

  def on_movie_clicked(self, w, e):
    self.toggle_controls()

  def on_message(self, bus, message):
    t = message.type
    if t == gst.MESSAGE_ASYNC_DONE:
      if self.app_state == "PLAY":
        if self.duration is None:  # 1st time only
          self.duration = self.player.query_duration (gst.FORMAT_TIME, None) [0]
          print "Duration %s" % (self.duration)
          self.change_rate (self.rate, pos = 0)
          self.player.set_state (gst.STATE_PLAYING)
    if t == gst.MESSAGE_EOS:
      self.set_app_state("STOP")
      if len (self.playlist) > 0: self.on_next(None)
    elif t == gst.MESSAGE_ERROR:
      err, debug = message.parse_error()
      print "Error: %s" % err, debug
      self.set_app_state("STOP")

  def on_sync_message(self, bus, message):
    if message.structure is None: return
    message_name = message.structure.get_name()
    if message_name == "prepare-xwindow-id":
      imagesink = message.src
      imagesink.set_property("force-aspect-ratio", True)
      gtk.gdk.threads_enter()
      imagesink.set_xwindow_id(self.movie_window.window.xid)
      gtk.gdk.threads_leave()

GTK_Main(prog_options, prog_args)
gtk.gdk.threads_init()
gtk.main()
