#+TITLE: Playbin2 Player
#+OPTIONS: toc:nil

/Gstreamer-based video player with variable speed playback support/

  * Home page :: [[http://danmbox.github.com/playbin2player]]
  * Downloads :: [[https://github.com/danmbox/playbin2player][github]], [[https://github.com/danmbox/playbin2player/releases][releases]]
  * Author :: [[http://alumnus.caltech.edu/~muresan/][Dan A. Muresan]] (danmbox at gmail dot com)


* DESCRIPTION

  [[http://danmbox.github.com/playbin2player][Playbin2 Player]] is a
  pure gstreamer-based video player with support for faster / slower
  playback. It only requires Python 2.5, so Maemo devices (e.g.  Nokia
  N900) can run it. Gstreamer playback is hardware-accelerated on
  Maemo (as well as other mobile / embedded platforms), so pb2player
  may have an advantage over other media players.

  This is the *development branch* of pb2player. The latest current
  stable release series is
  [[https://github.com/danmbox/playbin2player/tree/v1.0.x][v1.0.x]].


* DEPENDENCIES

  * gstreamer-0.10 and PyGST

  * Gtk+ 2 and PyGTK

  * Python 2.5+


* INSTALLING

  Download and unpack a
  [[https://github.com/danmbox/playbin2player/releases][release]] to
  your preferred destination and follow the relevant README.

  For the development branch, download with =git=, then run
  =pb2player= directly from the source folder:

  =git clone git://github.com/danmbox/playbin2player.git=


* RUNNING

  Run =pb2player [ mediafile.ext | playlist.m3u ]=

  The player accepts only m3u playlists.


* COPYRIGHT

  Copyright 2013 Dan A. Muresan

  See LICENSE.txt for licensing information.
