#+TITLE: Playbin2 Player
#+OPTIONS: toc:nil

/Gstreamer-based video player with variable speed playback support/

  * Home page :: [[http://danmbox.github.com/playbin2player]]
  * Downloads :: [[https://github.com/danmbox/playbin2player][github]], [[https://github.com/danmbox/playbin2player/releases][releases]]
  * Author :: [[http://alumnus.caltech.edu/~muresan/][Dan A. Muresan]] (danmbox at gmail dot com)


* DESCRIPTION

  [[http://danmbox.github.com/playbin2player][Playbin2 Player]] is a pure gstreamer-based video player with support for 
  faster / slower playback. As it works on Python 2.5, Maemo devices (e.g. 
  Nokia N900) can run it.

  This is the *1.0.x release series*; the project homepage contains
  more recent developments.


* DEPENDENCIES

  * gstreamer-0.10 and PyGST

  * Gtk+ 2 and PyGTK

  * Python 2.5+


* INSTALLING

  Download and unpack a [[https://github.com/danmbox/playbin2player/releases][release]]
  to your preferred destination, or use git:

  =git clone -b v1.0.x git://github.com/danmbox/playbin2player.git=

  Run =make install=, or, on Debian, =make debuild= (then install the
  =.deb= from =/tmp=); or if you want to run =pb2player= directly from
  the source folder, no installation is required.

* RUNNING

  Run =pb2player [ mediafile.ext | playlist.m3u ]=

  The player accepts only m3u playlists.

* COPYRIGHT

  Copyright 2013 Dan A. Muresan

  See LICENSE.txt for licensing information.
